export const CREATE_WORKSPACE = "CREATE_WORKSPACE";
export const UPDATE_WORKSPACE = "UPDATE_WORKSPACE";
export const DELETE_WORKSPACE = "DELETE_WORKSPACE";
export const FETCH_ALL_WORKSPACE = "FETCH_ALL_WORKSPACE";
export const FETCH_WORKSPACE = "FETCH_WORKSPACE";
export const OPEN_WORKSPACE = "OPEN_WORKSPACE";

export const CREATE_BIN = "CREATE_BIN";
export const UPDATE_BIN = "UPDATE_BIN";
export const DELETE_BIN = "DELETE_BIN";
export const FETCH_ALL_BIN = "FETCH_ALL_BIN";

export const CREATE_NOTE = "CREATE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const FETCH_ALL_NOTE = "FETCH_ALL_NOTE";

export const AUTH = "AUTH";
export const SIGNOUT = "SIGNOUT";
